name: Build and test

on:
  push:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run tests
      run: |
        chmod +x run-tests.sh
        ./run-tests.sh

    - name: Build package to publish
      run: |
        .venv/bin/python setup.py sdist bdist_wheel

    - name: Freeze packages
      run: |
          .venv/bin/pip freeze > requirements.txt

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: dist
          path: dist

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: requirements.txt
          path: requirements.txt


